[2025-05-27T01:11:28.163+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-27T01:11:28.182+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_sql_data manual__2025-05-27T01:11:24.526518+00:00 [queued]>
[2025-05-27T01:11:28.194+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_sql_data manual__2025-05-27T01:11:24.526518+00:00 [queued]>
[2025-05-27T01:11:28.197+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2025-05-27T01:11:28.213+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_sql_data> on 2025-05-27 01:11:24.526518+00:00
[2025-05-27T01:11:28.236+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1530) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-27T01:11:28.243+0000] {standard_task_runner.py:63} INFO - Started process 1535 to run task
[2025-05-27T01:11:28.244+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'supplier_data_etl_pipeline', 'extract_sql_data', 'manual__2025-05-27T01:11:24.526518+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/supplier_dag.py', '--cfg-path', '/tmp/tmpl8wi2py9']
[2025-05-27T01:11:28.252+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask extract_sql_data
[2025-05-27T01:11:28.367+0000] {task_command.py:426} INFO - Running <TaskInstance: supplier_data_etl_pipeline.extract_sql_data manual__2025-05-27T01:11:24.526518+00:00 [running]> on host 295abcd9c300
[2025-05-27T01:11:28.494+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supplier_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T01:11:24.526518+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T01:11:24.526518+00:00'
[2025-05-27T01:11:28.502+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-27T01:11:28.519+0000] {etl.py:45} INFO - connected to db source
[2025-05-27T01:11:28.550+0000] {etl.py:47} INFO - queried db source
[2025-05-27T01:11:28.552+0000] {etl.py:49} INFO - closed db connection
[2025-05-27T01:11:28.559+0000] {etl.py:51} INFO - db source pickled
[2025-05-27T01:11:28.560+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-27T01:11:28.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-27T01:11:28.570+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=supplier_data_etl_pipeline, task_id=extract_sql_data, execution_date=20250527T011124, start_date=20250527T011128, end_date=20250527T011128
[2025-05-27T01:11:28.601+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-27T01:11:28.622+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-27T01:11:28.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
